use anyhow::{Context, Result, bail};
use std::path::PathBuf;

const SPEC: &str = "vendor/omnigent-0.3.0.dev0/openapi.json";
const OUT: &str = "crates/lens-client/src/generated.rs";

fn main() -> Result<()> {
    let cmd = std::env::args().nth(1).unwrap_or_default();
    match cmd.as_str() {
        "codegen" => codegen(),
        other => bail!("unknown xtask command: {other:?} (expected: codegen)"),
    }
}

fn codegen() -> Result<()> {
    let root = workspace_root()?;
    let spec_path = root.join(SPEC);
    let raw = std::fs::read_to_string(&spec_path)
        .with_context(|| format!("read {}", spec_path.display()))?;
    let doc: serde_json::Value = serde_json::from_str(&raw)?;

    let schemas = doc
        .get("components")
        .and_then(|c| c.get("schemas"))
        .and_then(|s| s.as_object())
        .context("openapi.json has no components.schemas")?;

    let mut settings = typify::TypeSpaceSettings::default();
    settings.with_derive("PartialEq".into());
    let mut type_space = typify::TypeSpace::new(&settings);

    let mut parsed: Vec<(String, schemars::schema::Schema)> = Vec::new();
    for (name, schema) in schemas {
        let schema: schemars::schema::Schema = serde_json::from_value(schema.clone())
            .with_context(|| format!("schema {name} is not valid JSON Schema"))?;
        parsed.push((name.clone(), schema));
    }

    if let Err(e) = type_space.add_ref_types(parsed.iter().map(|(n, s)| (n.as_str(), s.clone()))) {
        let mut failures: Vec<(String, String)> = Vec::new();
        for (name, schema) in &parsed {
            let mut probe = typify::TypeSpace::new(&settings);
            if let Err(err) = probe.add_ref_types(std::iter::once((name.as_str(), schema.clone())))
            {
                failures.push((name.clone(), err.to_string()));
            }
        }
        let skipped_path = root.join("vendor/omnigent-0.3.0.dev0/SKIPPED.md");
        let body: String = failures
            .iter()
            .map(|(name, reason)| format!("- {name}: {reason}"))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n";
        std::fs::write(&skipped_path, &body)
            .with_context(|| format!("write {}", skipped_path.display()))?;
        let failed_names: Vec<&str> = failures.iter().map(|(n, _)| n.as_str()).collect();
        bail!(
            "typify batch add_ref_types failed: {e}; individually-failing schemas: {}",
            failed_names.join(", ")
        );
    }

    let tokens = type_space.to_stream();
    let file: syn::File = syn::parse2(tokens).context("parse generated tokens")?;
    let pretty = prettyplease::unparse(&file);

    let header = "// @generated by `cargo run -p xtask -- codegen` from \
vendor/omnigent-0.3.0.dev0/openapi.json — DO NOT EDIT BY HAND.\n\
#![allow(clippy::all)]\n\n";
    let out_path = root.join(OUT);
    std::fs::write(&out_path, format!("{header}{pretty}"))
        .with_context(|| format!("write {OUT}"))?;

    // prettyplease gives us readable output, but `cargo fmt` (rustfmt) formats
    // differently — run rustfmt as the final pass so the committed file is
    // rustfmt-canonical and `cargo fmt --check` stays a no-op on it.
    let status = std::process::Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&out_path)
        .status()
        .context("run rustfmt on generated.rs (is the rustfmt component installed?)")?;
    if !status.success() {
        bail!("rustfmt failed on {OUT} (exit {:?})", status.code());
    }

    println!("wrote {OUT} ({} schemas)", schemas.len());
    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    // xtask is invoked from the workspace root via `cargo run -p xtask`.
    Ok(std::env::current_dir()?)
}
