#!/usr/bin/env bash
# WP0 Task 4 — generate vendor/<dir>/adoption.toml: an exhaustive adopt/adapt/exclude
# inventory of every pinned wrapper file (45) and every Ghostty src/** mirror file.
#
# Usage: UPSTREAM=/tmp/gpui-ghostty-e3025981 ./scripts/generate-terminal-adoption.sh vendor/gpui-ghostty-e3025981
#
# Wrapper rows carry the exact `git ls-files` paths (VT crates keep the `crates/` prefix;
# examples/.github/LICENSE/docs are repo-root). Mirror rows are relative to vendor/ghostty/src
# (the leading `src/` is stripped). Task 5 promotes the compile-closure subset to adopt/adapt.
set -euo pipefail

UPSTREAM="${UPSTREAM:?set UPSTREAM to the pinned gpui-ghostty checkout}"
OUT_DIR="${1:?usage: generate-terminal-adoption.sh <vendor-dir>}"
OUT="$OUT_DIR/adoption.toml"

emit_row() { # kind path disposition license reason
  printf '[[%s]]\npath = "%s"\ndisposition = "%s"\nlicense = "%s"\nreason = "%s"\n\n' \
    "$1" "$2" "$3" "$4" "$5"
}

wrapper_rule() { # path -> "disposition|reason"  (first match wins)
  local p="$1"
  case "$p" in
    examples/pty_terminal/*|examples/split_pty_terminal/*) echo "exclude|local PTY example" ;;
    .github/*)                                             echo "exclude|packaging/CI" ;;
    LICENSE|LICENSE-*)                                     echo "exclude|upstream license retained verbatim under licenses/; not imported as source" ;;
    Cargo.lock|README.md|ROADMAP.md|AGENTS.md|.gitignore|docs/*) echo "exclude|lockfile/docs not imported" ;;
    crates/gpui_ghostty_terminal/src/view/mod.rs|crates/gpui_ghostty_terminal/src/font.rs|crates/gpui_ghostty_terminal/src/tests.rs|examples/basic_terminal/src/main.rs) echo "adapt|GPUI 0.2.2 reconciliation surface" ;;
    crates/gpui_ghostty_terminal/src/session.rs)          echo "exclude|PTY host — omnigent owns PTY" ;;
    crates/ghostty_vt_sys/*|crates/ghostty_vt/src/lib.rs|crates/ghostty_vt/Cargo.toml) echo "adapt|FFI/VT boundary" ;;
    crates/ghostty_vt/tests/*.rs)                         echo "adopt|VT corpus for WP7" ;;
    *)                                                     echo "adapt|wrapper build/port surface" ;;
  esac
}

# Mirror pre-closure exclude overlay: everything is exclude at Task 4; Task 5 promotes the closure.
mirror_reason() { # src-relative path -> reason
  local p="$1"
  case "$p" in
    termio/*|apprt/*|renderer/*|font/*|cli/*|shell-integration/*|inspector/*|benchmark/*|stb/*) echo "outside slim VT compile closure (subsystem)" ;;
    *sixel*|*kitty*|*osc1337*|*image*) echo "outside slim VT compile closure (inline-graphics/parse trim)" ;;
    *) echo "not in slim compile closure (promoted by Task 5 if required)" ;;
  esac
}

{
  echo "# GENERATED by scripts/generate-terminal-adoption.sh — do not hand-edit wrapper rows."
  echo "# Task 5 promotes the compile-closure mirror subset to adopt/adapt in place."
  echo

  # --- wrappers (45) ---
  git -C "$UPSTREAM" ls-files \
    | grep -v '^vendor/ghostty' | grep -v 'ghostty_src' | grep -v '^\.gitmodules$' | sort \
    | while IFS= read -r p; do
        rule="$(wrapper_rule "$p")"; disp="${rule%%|*}"; reason="${rule#*|}"
        emit_row wrapper "$p" "$disp" "Apache-2.0" "$reason"
      done

  # --- mirrors (ghostty src/**, src/ stripped) ---
  git -C "$UPSTREAM/vendor/ghostty" ls-files 'src/**' | sort \
    | while IFS= read -r p; do
        rel="${p#src/}"
        emit_row mirror "$rel" "exclude" "MIT" "$(mirror_reason "$rel")"
      done
} > "$OUT"

wc=$(grep -c '^\[\[wrapper\]\]' "$OUT")
mc=$(grep -c '^\[\[mirror\]\]' "$OUT")
echo "wrote $OUT: $wc wrapper rows, $mc mirror rows"
